language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-2_Labs_Myshkin
  - make -j
  - ./vectortest/vectortest
  - ./matrixtest/matrixtest
notifications:
  email: false
